### ISSUE TITLE
Can't flash nanoESP32-C3

### ISSUE THREAD

**Issue by mtuxpe** [wuxx/nanoESP32-C3#1]
I can't flash the board using esp-idf .  
I can't flash using ESP32 Flash Download Tool.
My environment is installed correctly. 
I can flash  ESP32-C3S_Kit and also ESP32-C3-DevKitC

**Comment by wuxx** [comment]
hello, do you flash under windows?
if use windows, there is a bug in esptool.py, the nanoESP32-C3 
please check this issue, 
https://github.com/espressif/esptool/issues/655
and a workaround is here 
https://github.com/wuxx/esptool/commit/723810dac013107cd95f70686e394b2f6a5fc247

**Comment by mtuxpe** [comment]
Thanks for feedback. I use linux and windows but for initial tests I'm
using windows.
