### ISSUE TITLE
Serial output <ESPLink:Overflow> error when printing to terminal

### ISSUE THREAD

**Issue by annonymouspotato** [wuxx/nanoESP32-C3#4]
I'm having trouble printing out the output from the serial terminal. It keeps giving me a ESPLINK:Overflow error at the end of the string.

> ESP-ROM:esp32c3-api1-20210207
> Build:Feb  7 2021
> rst:0x1 (POWERON),boot:0xc (SPI_FAST_FLASH_BOOT)
> SPIWP:0xee
> mode:DIO, clock div:1
> load:0x3fcd6100,len:0x16b8
> load:0x403ce000,len:0x930
> load:0x403d0000,len:0x2d40
> SHA-256 comparison failed:
> Calculated: a882d00141a66940bc39c1d3f34283def35ff626a4350238e0b4f70d513f2d61
> Expected: 436193303ace014b7d56b63e7968b151ed23ccba24c9234e9ab0de048acc788a
> Attempting to boot anyway...
> entry 0x403ce000
> I (48) boot: ESP-IDF v4.4-dirty 2nd stage bootloader
> I (49) boot: compile time 11:08:44
> I (49) boot: chip revision: 3
> I (51) boot.esp32c3: SPI Speed      : 80MHz
> I (55) boot.esp32c3: SPI Mode       : DIO
> I (60) boot.esp32c3: SPI Flash Size : 4MB
> I (65) boot: Enabling RNG early entropy source...
> I (70) boot: Partition Table:
> I (74) boot: ## Label            Usage          Type ST Offset   Length
> I (81) boot:  0 nvs             <ESPLink:Overflow>
> [0m
> I<ESPLink:Overflow>
> f000 00001000<ESPLink:Overflow>
>      00 00 00<ESPLink:Overflow>
> n table
> <ESPLink:Overflow>
> c020020 size=<ESPLink:Overflow>
> 1: paddr=0001<ESPLink:Overflow>
> I (126) esp_i<ESPLink:Overflow>
>  ( 29060) loa<ESPLink:Overflow>
>  vaddr=420000<ESPLink:Overflow>
> I (155<ESPLink:Overflow>
> ize=03ea0h ( <ESPLink:Overflow>
> r=00039578 va<ESPLink:Overflow>
>  boot: Loaded<ESPLink:Overflow>
> oot: Disablin<ESPLink:Overflow>
> t: Pro cpu up<ESPLink:Overflow>
> I (193<ESPLink:Overflow>
> I (193) cpu_s<ESPLink:Overflow>
> plication inf<ESPLink:Overflow>
> <ESPLink:Overflow>
> tart: App <ESPLink:Overflow>
>     Apr 12 20<ESPLink:Overflow>
> :  21c3b3beb5<ESPLink:Overflow>
> v4.4-dirtySPLink:Overflow>
> or dynamic al<ESPLink:Overflow>
> 032B90 (202 K<ESPLink:Overflow>
> 001F060 (124 <ESPLink:Overflow>
>  len 00001FE0<ESPLink:Overflow>
> ip: genericSPLink:Overflow>
> (258) sleep: <ESPLink:Overflow>
> 32mI (264) sl<ESPLink:Overflow>
> n
> SPLink:Overflow>

**Comment by wuxx** [comment]
hello, can you check the ESPLink version, please check the DETAIL.TXT in ESPLink USB DISK

**Comment by annonymouspotato** [comment]
From DETAIL.TXT

> # ESPLink v1.1 for nanoESP32-C3 by MuseLab - see muselab-tech.com
> Build Time: Oct  9 2021 14:20:40

**Comment by wuxx** [comment]
please try to upgrade to v1.1c
https://github.com/wuxx/nanoESP32-C3/blob/master/firmware/interface_v1.1c_for_c3.bin
Here are the upgrade steps

```
1. create a blank file called START_BL.ACT in ESPLink USB DISK
$touch /media/pi/ESPLink/START_BL.ACT
2. wait for a while, the ESPLink will enter into bootloader, a new USB DISK called MAINTAINENCE will appear
3. copy the firmware into the MAINTAINENCE
$cp interface_v1.1c_for_c3.bin /media/pi/MAINTAINENCE
4. wait for a while, after upgrade done, ESPLink USB DISK will appear, please check the ESPLink/DETAIL.TXT to see the new version v1.1c
```

**Comment by annonymouspotato** [comment]
I've upgraded the firmware and the problem is now resolved. Thanks

`ESPLink v1.1c for nanoESP32-C3 by MuseLab - see muselab-tech.com
Build Time: Nov  7 2021 14:08:30`
